controller:
  # Service 타입 (LoadBalancer, NodePort, ClusterIP)
  serviceType: LoadBalancer

  # 초기 플러그인 설치
  installPlugins:
    - kubernetes:4256.v4b_a_0b_e3f_c8e5
    - git:5.7.0
    - credentials-binding:700.v8133766e4ac7
    - workflow-aggregator:600.vb_57cdd26fdd7
    - docker-workflow:580.vc0c340686b_54

  # Jenkins Controller ServiceAccount
  serviceAccount:
    create: true
    name: jenkins

  # Java 옵션 (초기 설정 마법사 스킵)
  javaOpts: "-Djenkins.install.runSetupWizard=false"

  # 리소스 제한
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"

# Agent 설정 (Kaniko Pod 템플릿용)
agent:
  enabled: true
  namespace: skala-practice
  serviceAccount: jenkins-agent